language: rust
rust:
  - nightly

os:
  - linux
  - osx
  - windows

script:
  - bash build.sh

before_deploy:
      - tar cvzf release-$TRAVIS_OS_NAME.tgz -C target/release assignment4 data

deploy:
      provider: releases
      # token: # Given by GITHUB_TOKEN env
      file: release-$TRAVIS_OS_NAME.tgz
      edge: true
      on:
        tags: true
